language: rust
os:
  - linux
  - osx

#addons:
  #homebrew:
    #packages:
      #- tmux
    #update: true

rust:
  - stable
  - beta
  - nightly

env:
  #- TMUX_VERSION=0.8
  #- TMUX_VERSION=0.9
  #- TMUX_VERSION=1.0
  #- TMUX_VERSION=1.1
  #- TMUX_VERSION=1.2
  #- TMUX_VERSION=1.3
  #- TMUX_VERSION=1.4
  #- TMUX_VERSION=1.5
  #- TMUX_VERSION=1.6
  #- TMUX_VERSION=1.7
  #- TMUX_VERSION=1.8
  #- TMUX_VERSION=1.9
  #- TMUX_VERSION=1.9a
  #- TMUX_VERSION=2.0
  #- TMUX_VERSION=2.1
  #- TMUX_VERSION=2.2
  #- TMUX_VERSION=2.3
  #- TMUX_VERSION=2.4
  #- TMUX_VERSION=2.5
  - TMUX_VERSION=2.6 CRATE_FEATURE=tmux_2_6
  #- TMUX_VERSION=2.7
  - TMUX_VERSION=2.8 CRATE_FEATURE=tmux_2_8
  #- TMUX_VERSION=2.9
  #- TMUX_VERSION=2.9a
  #- TMUX_VERSION=3.0
  #- TMUX_VERSION=3.0a
  #- TMUX_VERSION=3.1
  #- TMUX_VERSION=master CRATE_FEATURE=tmux_X_X

before_script:
  - export PATH=$HOME/build/tmux-$TMUX_VERSION/bin:$PATH
  - ./scripts/tmux_setup.sh

script:
  #- cargo build --verbose
  #- cargo test --verbose
  #- cargo build --features tmux_2_6 --verbose
  #- cargo test --features tmux_2_6 --verbose
  - cargo build --features $CRATE_FEATURE --verbose
  - cargo test --features $CRATE_FEATURE --verbose
