# NOTE: based on .travis.yml file created by tmuxp project contributors:
# [tmuxp](https://github.com/tmux-python/tmuxp/blob/master/.travis.yml)
language: rust
os:
  - linux
  #- osx

addons:
  #homebrew:
    #packages:
      #- tmux
    #update: true

  apt:
    packages:
      - libevent-dev
      - libncurses-dev

rust:
  - stable
  - beta
  - nightly

cache:
  - apt
  - directories:
    - ~/tmux/source
    - ~/tmux/build

env:
  - TMUX_VERSION=0.8 CRATE_FEATURE=tmux_0_8
  - TMUX_VERSION=0.9 CRATE_FEATURE=tmux_0_9
  - TMUX_VERSION=1.0 CRATE_FEATURE=tmux_1_0
  - TMUX_VERSION=1.1 CRATE_FEATURE=tmux_1_1
  - TMUX_VERSION=1.2 CRATE_FEATURE=tmux_1_2
  - TMUX_VERSION=1.3 CRATE_FEATURE=tmux_1_3
  - TMUX_VERSION=1.4 CRATE_FEATURE=tmux_1_4
  - TMUX_VERSION=1.5 CRATE_FEATURE=tmux_1_5
  - TMUX_VERSION=1.6 CRATE_FEATURE=tmux_1_6
  - TMUX_VERSION=1.7 CRATE_FEATURE=tmux_1_7
  - TMUX_VERSION=1.8 CRATE_FEATURE=tmux_1_8
  - TMUX_VERSION=1.9 CRATE_FEATURE=tmux_1_9
  - TMUX_VERSION=1.9a CRATE_FEATURE=tmux_1_9a
  - TMUX_VERSION=2.0 CRATE_FEATURE=tmux_2_0
  - TMUX_VERSION=2.1 CRATE_FEATURE=tmux_2_1
  - TMUX_VERSION=2.2 CRATE_FEATURE=tmux_2_2
  - TMUX_VERSION=2.3 CRATE_FEATURE=tmux_2_3
  - TMUX_VERSION=2.4 CRATE_FEATURE=tmux_2_4
  - TMUX_VERSION=2.5 CRATE_FEATURE=tmux_2_5
  - TMUX_VERSION=2.6 CRATE_FEATURE=tmux_2_6
  - TMUX_VERSION=2.7 CRATE_FEATURE=tmux_2_7
  - TMUX_VERSION=2.8 CRATE_FEATURE=tmux_2_8
  - TMUX_VERSION=2.9 CRATE_FEATURE=tmux_2_9
  - TMUX_VERSION=2.9a CRATE_FEATURE=tmux_2_9a
  - TMUX_VERSION=3.0 CRATE_FEATURE=tmux_3_0
  - TMUX_VERSION=3.0a CRATE_FEATURE=tmux_3_0a
  - TMUX_VERSION=3.1 CRATE_FEATURE=tmux_3_1
  - TMUX_VERSION=3.1a CRATE_FEATURE=tmux_3_1a
  - TMUX_VERSION=3.1b CRATE_FEATURE=tmux_3_1b
  - TMUX_VERSION=master CRATE_FEATURE=tmux_X_X

matrix:
  allow_failures:
      # failing tmux compilation
    - env: TMUX_VERSION=0.8 CRATE_FEATURE=tmux_0_8
    - env: TMUX_VERSION=0.9 CRATE_FEATURE=tmux_0_9
    - env: TMUX_VERSION=1.0 CRATE_FEATURE=tmux_1_0
    - env: TMUX_VERSION=1.1 CRATE_FEATURE=tmux_1_1
    - env: TMUX_VERSION=1.2 CRATE_FEATURE=tmux_1_2
    - env: TMUX_VERSION=1.3 CRATE_FEATURE=tmux_1_3
    - env: TMUX_VERSION=1.4 CRATE_FEATURE=tmux_1_4
      # failing docs
    - env: TMUX_VERSION=1.5 CRATE_FEATURE=tmux_1_5
      # failing brand new version
    #- env: TMUX_VERSION=master CRATE_FEATURE=tmux_X_X

before_script:
  - mkdir -p ~/tmux/source
  - mkdir -p ~/tmux/build/tmux-$TMUX_VERSION
  - if [[ ! -d ~/tmux/source/tmux-$TMUX_VERSION ]]; then git clone https://github.com/tmux/tmux.git ~/tmux/source/tmux-$TMUX_VERSION; fi
  - cd ~/tmux/source/tmux-$TMUX_VERSION
  - git checkout $TMUX_VERSION
  - export PATH=$HOME/tmux/build/tmux-$TMUX_VERSION/bin:$PATH
  - if [[ $TMUX_VERSION == "master" || ! $(tmux -V | grep $TMUX_VERSION) ]]; then sh autogen.sh; fi
  - if [[ $TMUX_VERSION == "master" || ! $(tmux -V | grep $TMUX_VERSION) ]]; then ./configure --prefix=$HOME/tmux/build/tmux-$TMUX_VERSION && make && make install; fi
  - cd $TRAVIS_BUILD_DIR
  - tmux -V

script:
  - cargo build --features $CRATE_FEATURE --no-default-features --verbose
  - cargo test --features $CRATE_FEATURE --no-default-features --verbose
