[package]
name = "tmux_interface"
version = "0.0.3"
authors = ["Anton Gepting <anton.gepting@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust language library for communication with TMUX via CLI"
readme = "README.md"
keywords = ["tmux", "cli", "interface"]
categories = ["api-bindings", "command-line-utilities", "command-line-interface"]
repository = "https://github.com/AntonGepting/tmux-interface-rs"


[dependencies]
regex = "1.1.6"
