[package]
name = "tmux_interface"
version = "0.0.1"
authors = ["Anton Gepting <anton.gepting@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust language library for communication with TMUX via CLI"


[dependencies]
regex = "*"
serde_yaml = "*"

