name: GitHub Actions

on:
  push:
    branches:
      - main
      - dev
  #pull_request:
    #branches:
    # - main
    # - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tmux_version: |
          [["0.8", "tmux_0_8"], ["0.9", "tmux_0_9"], ["1.0", "tmux_1_0"],
          ["1.1", "tmux_1_1"], ["1.2", "tmux_1_2"], ["1.3", "tmux_1_3"],
          ["1.4", "tmux_1_4"], ["1.5", "tmux_1_5"], ["1.6", "tmux_1_6"],
          ["1.7", "tmux_1_7"], ["1.8", "tmux_1_8"], ["1.9", "tmux_1_9"],
          ["1.9a", "tmux_1_9a"], ["2.0", "tmux_2_0"], ["2.1", "tmux_2_1"],
          ["2.2", "tmux_2_2"], ["2.3", "tmux_2_3"], ["2.4", "tmux_2_4"],
          ["2.5", "tmux_2_5"], ["2.6", "tmux_2_6"], ["2.7", "tmux_2_7"],
          ["2.8", "tmux_2_8"], ["2.9", "tmux_2_9"], ["2.9a", "tmux_2_9a"],
          ["3.0", "tmux_3_0"], ["3.0a", "tmux_3_0a"], ["3.1", "tmux_3_1"],
          ["3.1a", "tmux_3_1a"], ["3.1b", "tmux_3_1b"], ["3.2c", "tmux_3_2c"],
          ["master", "tmux_X_X"]]

    steps:
      - uses: actions/checkout@v2

      - name: Setup tmux build cache for tmux ${{ matrix.tmux_version }}
        id: tmux-build-cache
        uses: actions/cache@v1
        with:
          path: ~/tmux-builds/tmux-${{ matrix.tmux_version }}
          key: tmux-${{ matrix.tmux_version }}

      - name: Build tmux ${{ matrix.tmux_version }}
        if: steps.tmux-build-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt install libevent-dev libncurses5-dev libtinfo-dev libutempter-dev bison
          mkdir ~/tmux-builds
          mkdir ~/tmux-src
          git clone https://github.com/tmux/tmux.git ~/tmux-src/tmux-${{ matrix.tmux_version }}
          cd ~/tmux-src/tmux-${{ matrix.tmux_version }}
          git checkout ${{ matrix.tmux_version }}
          sh autogen.sh
          ./configure --prefix=$HOME/tmux-builds/tmux-${{ matrix.tmux_version }} && make && make install
          export PATH=$HOME/tmux-builds/tmux-${{ matrix.tmux_version }}/bin:$PATH
          cd ~
          tmux -V

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
