name: GitHub Actions

on:
  push:
    branches:
      - main
      - dev
  #pull_request:
    #branches:
    # - main
    # - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tmux_version: ["0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5",
          "1.6", "1.7", "1.8", "1.9", "1.9a", "2.0", "2.1", "2.2", "2.3",
          "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "2.9a", "3.0", "3.0a",
          "3.1", "3.1a", "3.1b", "3.2c", "master"]
        crate_feature: ["tmux_0_8", "tmux_0_9", "tmux_1_0", "tmux_1_1",
          "tmux_1_2", "tmux_1_3", "tmux_1_4", "tmux_1_5", "tmux_1_6",
          "tmux_1_7", "tmux_1_8", "tmux_1_9", "tmux_1_9a", "tmux_2_0",
          "tmux_2_1", "tmux_2_2", "tmux_2_8", "tmux_2_9", "tmux_2_9a",
          "tmux_3_0", "tmux_3_0a", "tmux_3_1", "tmux_3_1a", "tmux_3_1b",
          "tmux_3_1c", "tmux_X_X"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup tmux build cache for tmux ${{ matrix.tmux_version }}
        id: tmux-build-cache
        uses: actions/cache@v1
        with:
          path: ~/tmux-builds/tmux-${{ matrix.tmux_version }}
          key: tmux-${{ matrix.tmux_version }}

      - name: Build tmux ${{ matrix.tmux_version }}
        if: steps.tmux-build-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt install libevent-dev libncurses5-dev libtinfo-dev libutempter-dev bison
          mkdir ~/tmux-builds
          mkdir ~/tmux-src
          git clone https://github.com/tmux/tmux.git ~/tmux-src/tmux-${{ matrix.tmux_version }}
          cd ~/tmux-src/tmux-${{ matrix.tmux_version }}
          git checkout ${{ matrix.tmux_version }}
          sh autogen.sh
          ./configure --prefix=$HOME/tmux-builds/tmux-${{ matrix.tmux_version }} && make && make install
          export PATH=$HOME/tmux-builds/tmux-${{ matrix.tmux_version }}/bin:$PATH
          cd ~
          tmux -V

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
